//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyStorm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyStorm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 鳞弹_0_0_24_24_12_13_2_0
        ///鳞弹_24_0_24_24_12_13_2_1
        ///鳞弹_48_0_24_24_12_13_2_2
        ///鳞弹_72_0_24_24_12_13_2_3
        ///鳞弹_96_0_24_24_12_13_2_4
        ///鳞弹_120_0_24_24_12_13_2_5
        ///鳞弹_144_0_24_24_12_13_2_6
        ///鳞弹_168_0_24_24_12_13_2_7
        ///环圆弹_192_0_24_24_12_12_3_0
        ///环圆弹_216_0_24_24_12_12_3_1
        ///环圆弹_240_0_24_24_12_12_3_2
        ///环圆弹_264_0_24_24_12_12_3_3
        ///环圆弹_288_0_24_24_12_12_3_4
        ///环圆弹_312_0_24_24_12_12_3_5
        ///环圆弹_336_0_24_24_12_12_3_6
        ///环圆弹_360_0_24_24_12_12_3_7
        ///小玉_0_24_24_24_12_12_3_0
        ///小玉_24_24_24_24_12_12_3_1
        ///小玉_48_24_24_24_12_12_3_2
        ///小玉_72_24_24_24_12 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
    }
}
