//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyStorm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyStorm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鳞弹红_0_0_24_24_12_13_2_0
        ///鳞弹紫_24_0_24_24_12_13_2_1
        ///鳞弹蓝_48_0_24_24_12_13_2_2
        ///鳞弹青_72_0_24_24_12_13_2_3
        ///鳞弹绿_96_0_24_24_12_13_2_4
        ///鳞弹黄_120_0_24_24_12_13_2_5
        ///鳞弹橙_144_0_24_24_12_13_2_6
        ///鳞弹白_168_0_24_24_12_13_2_7
        ///环圆弹红_192_0_24_24_12_12_3_0
        ///环圆弹紫_216_0_24_24_12_12_3_1
        ///环圆弹蓝_240_0_24_24_12_12_3_2
        ///环圆弹青_264_0_24_24_12_12_3_3
        ///环圆弹绿_288_0_24_24_12_12_3_4
        ///环圆弹黄_312_0_24_24_12_12_3_5
        ///环圆弹橙_336_0_24_24_12_12_3_6
        ///环圆弹白_360_0_24_24_12_12_3_7
        ///小玉红_0_24_24_24_12_12_3_0
        ///小玉紫_24_24_24_24_12_12_3_1
        ///小玉蓝_48_24_24_24_12_12_3_2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
    }
}
